# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e02c14822effdaa8d6c174c5dd5873391ab557dc0e615a3733f76d30ba2080f7c8d56292d199d0dfaa8f323b7ef0a0c32f53e02621bd58bb2c9b386ea825cce2

test:
  secret_key_base: b87703a95249285806b3c424b1b7f485f14bdbb1242f669ffc66f43666314bf208f320acf6ebab7317864165ffa0bd8a4bb3bda07d3e28970f65f90796a57e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
